---
services:
  kanidm:
    container_name: kanidm
    image: ${KANIDM_IMAGE}
    restart: unless-stopped
    volumes:
      - ${KANIDM_DATA_DIR}:/data
    networks:
      - kanidm-net
    healthcheck:
      test: ["CMD", "/sbin/kanidmd", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  kanidm-cli:
    container_name: kanidm_cli
    image: ${KANIDM_TOOLS_IMAGE}
    profiles: ["cli"]
    volumes:
      - ${KANIDM_DATA_DIR}/kanidm-client-config:/root/.config/kanidm:ro
      - ${KANIDM_DATA_DIR}/kanidm_tokens:/root/.cache/kanidm_tokens
    networks:
      - kanidm-net
    entrypoint: ["kanidm"]

networks:
  kanidm-net:
    name: kanidm-net
